function pdemodel

% Geometry and parameter definitions
Width=50; % in unit microns
MetalWidth=1;
MetalThickness=0.5;
MetalLength=100;
MetalWGDistance=1;
WGWidth=0.5;
WGHeight=0.22;
kSi = 149e-6; % Thermal conductivity, W / (micron.K)
kSiO2 = 1.4e-6;
kAl = 250e-6;
Qsource=0.01;  % Heat source in the metal [W]
Q = Qsource / MetalThickness / MetalWGDistance / MetalLength;  % unit of W / micron^3;

%%%%%%%%%%%%%%
% code generated by Matlab PDE ToolBox:
%%%%%%%%%%%%%%
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',9);
set(ax,'DataAspectRatio',[1 1 1]);
set(ax,'PlotBoxAspectRatio',[10 6 1]);
set(ax,'XLim',[-10 10]);
set(ax,'YLim',[-10 2]);
set(ax,'XTickMode','auto');
set(ax,'YTickMode','auto');

% Geometry description:
pderect([-50 50 2 -2],'Oxide');
pderect([-0.5 0.5 1.22 1.72],'Metal');
pderect([-0.25 0.25 0 0.22],'Si');
pderect([-50 50 -2 -100],'SiSubstrate');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','Oxide+Metal+Si+SiSubstrate')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(14, 'neu', 1, '0','0')
pdesetbd(13, 'neu', 1, '0','0')
pdesetbd(10, 'neu', 1, '0','0')
pdesetbd(7,  'neu', 1, '0','0')
pdesetbd(6,  'neu', 1, '0','0')
pdesetbd(4,  'dir', 1, '1','0')

% Mesh generation:
setappdata(pde_fig,'Hgrad',1.3);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('on','mean',''));
setappdata(pde_fig,'MesherVersion','preR2013a');
pdetool('initmesh')
pdetool('refine')
pdetool('refine')

% PDE coefficients:
pdeseteq(1,...
  '1.4e-6!149e-6!250e-6!149e-6',...
  '0!0!0!0',...
  '(0)+(0).*(0.0)!(0)+(0).*(0.0)!(0.0002)+(0).*(0.0)!(0)+(0).*(0.0)',...
  '(1.0).*(1.0)!(1.0).*(1.0)!(1.0).*(1.0)!(1.0).*(1.0)',...
  '0:10',...
  '0.0',...
  '0.0',...
  '[0 100]')
setappdata(pde_fig,'currparam',...
  ['1.0!1.0!1.0!1.0            ';...
  '1.0!1.0!1.0!1.0            ';...
  '1.4e-6!149e-6!250e-6!149e-6';...
  '0!0!0.002!0                ';...
  '0!0!0!0                    ';...
  '0.0!0.0!0.0!0.0            '])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
  char('0','22368','10','pdeadworst',...
  '0.5','longest','0','1E-4','','fixed','Inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[1 1 1 1 1 1 7 1 0 0 0 1 1 1 0 0 0 1]);
setappdata(pde_fig,'colstring','');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');

% Solve PDE:
pdetool('solve')

%%% End of PDE ToolBox code.

%%%%%%%%%%%%%%%
% Extract data from PDE ToolBox and plot
%%%%%%%%%%%%%%%

pde_fig=findobj(allchild(0),'flat','Tag','PDETool');
u = get(findobj(pde_fig,'Tag','PDEPlotMenu'),'UserData');
h=findobj(get(pde_fig,'Children'),'flat','Tag','PDEMeshMenu');
hp=findobj(get(h,'Children'),'flat','Tag','PDEInitMesh');
he=findobj(get(h,'Children'),'flat','Tag','PDERefine');
ht=findobj(get(h,'Children'),'flat','Tag','PDEMeshParam');
p=get(hp,'UserData');
t=get(ht,'UserData');

% get geometry to overlay on plot
pdetool('export',2);
pause
g=evalin('base','g');
fid = wgeom(g, 'geom');

% Plot 2D data:
xlist =[-5:.05:5];
ylist =[-4:.05:2];
[X,Y] = meshgrid(xlist, ylist);
UXY=tri2grid(p,t,u,xlist,ylist);
figure; [c, h] = contourf(X,Y,UXY,20); colorbar;
c=colormap('hot'); c=c(end:-1:1,:); colormap(c)
hold all; h=pdegplot('geom');
set(h,'LineWidth',3,'Color','b');
global FONTSIZE
FONTSIZE=20;
xlabel ('x Position [\mum]','FontSize',FONTSIZE)
ylabel ('y Position [\mum]','FontSize',FONTSIZE)
pbaspect([ (xlist(end)-xlist(1))/(ylist(end)-ylist(1)) 1 1])
printfig ('thermal1');

% plot 1D
xlist =[0]; ylist =[-5:.01:2];
[X,Y] = meshgrid(xlist, ylist);
UXY=tri2grid(p,t,u,xlist,ylist);
figure; plot (Y, UXY,'LineWidth',3);
xlabel ('y Position [\mum]','FontSize',FONTSIZE)
ylabel ('Temperature','FontSize',FONTSIZE)
yl=ylim;ylim([0 yl(2)]); grid on
xlim([ylist(1) ylist(end)]);
printfig ('thermal2');

% Temperature inside waveguide
q=find(ylist>.09);
T_wg=UXY(q(1))

% Temperature inside metal
q=find(ylist>1.4);
T_metal=UXY(q(1))

% Thermal tuning efficiency calculations:
dndT = 1.87e-4;
FSR_fraction = dndT*T_wg*MetalLength / 1.55
mW_per_FSR = Qsource*1e3 / FSR_fraction


function printfig (file)
global FONTSIZE
set (gca, 'FontSize',FONTSIZE)
pdf = [ file '.pdf'];
print ('-dpdf', pdf);  system([ 'pdfcrop ' pdf ' ' pdf ]);
