gap=1e-07;
radius=5e-06;
wg_width=5e-07;
wg_thickness=2.2e-07;
Lc=0;
wavelength_start =1.5e-06;
wavelength_stop =1.6e-06;
mode_selection=1;
mesh_accuracy=2;

material_Clad = "SiO2 (Glass) - Palik";
material_Si   = "Si (Silicon) - Palik";

s_filename="dc_halfring_straight.dat";
switchtolayout;
cd;
dc_halfring_straight;
#rm("ebeam_dc_halfring_straight.fsp"); rm("ebeam_dc_halfring_straight_S-ParameterMatrixSweep/S-ParameterMatrixSweep_1.fsp"); rm("ebeam_dc_halfring_straight_S-ParameterMatrixSweep/S-ParameterMatrixSweep_2.fsp"); rm("ebeam_dc_halfring_straight_S-ParameterMatrixSweep/S-ParameterMatrixSweep_3.fsp");rm("ebeam_dc_halfring_straight_S-ParameterMatrixSweep/S-ParameterMatrixSweep_4.fsp");
#exit(2);
